# Netlify 빌드 및 배포 설정
[build]
  # 함수 코드가 들어있는 디렉토리를 지정합니다.
  functions = "netlify/functions"
  
  # 배포할 정적 파일(index.html 등)이 있는 디렉토리를 지정합니다.
  # 현재 프로젝트는 루트에 파일이 있으므로 "."으로 설정합니다.
  publish = "."

# API 요청을 함수로 연결해주는 규칙
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200